server:
  port: 8080

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: member
          uri: http://localhost:8081/
          predicates:
            - Path=/api/members/**
#        - id: product
#          uri: http://localhost:8082/
#          predicates:
#            - Path=/api/products/**
#        - id: order
#          uri: http://localhost:8083/
#          predicates:
#            - Path=/api/orders/**